api/urls.py
from django.urls import path, include
from rest_framework import routers
from api.views import ClinicalRecordsViewSet, PatientViewSet, PractitionerViewSet, UserViewSet


router = routers.DefaultRouter()
router.register("records/clinics", ClinicalRecordsViewSet)
router.register("records/patients", PatientViewSet)
router.register("records/practitioners", PractitionerViewSet)
router.register("records/users", UserViewSet)

urlpatterns = [
    path("", include(router.urls))
]

mwa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('api/', include('rest_framework.urls'),),
    path('api/', include('api.urls'),),
    path('admin/', admin.site.urls),
    path('accounts/', include('profiles.urls'),),
    path('accounts/', include('django.contrib.auth.urls'),),
    path('records/', include('records.urls'),),
]

profiles/urls.py
from django.urls import path
from django.views.generic import TemplateView
from profiles.views import SignUpView, StaffSignUpView, ProfileView

app_name="profiles"
urlpatterns = [
    # path('profile/', TemplateView.as_view(template_name="profiles/user.html"), name="profile"),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('staff/signup/', StaffSignUpView.as_view(), name='staff-signup'),
]

records/urls.py
from django.urls import path
from django.views.generic import TemplateView
from records.views import StatisticsReportView, MedicalReportsView, DashBoardView


app_name = "records"
urlpatterns = [
    # path("", TemplateView.as_view(template_name="records/dashboard.html"), name="dashboard"),
    path("", DashBoardView.as_view(), name="dashboard"),
    path("statistics/", StatisticsReportView.as_view(), name="statistics",),
    path("medical/", MedicalReportsView.as_view(), name="clinic-records",),
]

templates/includes/navbar.html
{% load static %}
<div class="container px-4">
    <nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
        <div class="container-fluid">
            <!-- Brand -->
            <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block navbar-brand" href="{% url 'home' %}">
                <img class="navbar-brand-img" width="40" height="40" src="{% static 'assets/img/brand/doctor-medical-mk-logo.png' %}" alt="Brand logo"> <span>MWA</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="mx-auto d-md-none">
                <img class="navbar-brand-img" width="30" height="30" src="{% static 'assets/img/brand/doctor-medical-mk-logo.png' %}" alt="Brand logo"> <span class="text-white font-weight-bold">MWA</span>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse-main">
                <!-- Collapse header -->
                <div class="navbar-collapse-header d-md-none">
                    <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{% url 'home' %}">
                        <img src="{% static 'assets/img/brand/doctor-medical-mk-logo.png' %}">
                        <span>MWA</span>
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                        <span></span>
                        <span></span>
                        </button>
                    </div>
                    </div>
                </div>
                <!-- Navbar items -->
                <ul class="navbar-nav ml-auto">
                    {% if not user.is_authenticated %}
                        <li class="nav-item btn btn-sm shadow-none--hover">
                            <a href="{% url 'profiles:signup' %}" class="nav-link">
                                <i class="ni ni-circle-08 text-pink"></i> Register
                            </a>
                        </li>
                        <li class="nav-item btn btn-sm shadow-none--hover">
                            <a href="{% url 'login' %}" class="nav-link">
                                <i class="ni ni-key-25 text-info"></i> Login
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <div class="media align-items-center">
                                <span class="avatar avatar-sm rounded-circle">
                                    <img alt="Image placeholder" src="https://ui-avatars.com/api/?name={{user.username}}">
                                </span>
                                <div class="media-body ml-2 d-none d-lg-block">
                                    <span class="mb-0 text-sm  font-weight-bold">Hi {{user.username}}!</span>
                                </div>
                                </div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                                <div class=" dropdown-header noti-title">
                                <h6 class="text-overflow m-0">Welcome!</h6>
                                </div>
                                <a href="#" class="dropdown-item">
                                    <i class="ni ni-single-02"></i>
                                    <span>My profile</span>
                                </a>
                                <a href="{% url 'records:dashboard' %}" class="dropdown-item">
                                    <i class="ni ni-ui-04"></i>
                                    <span>Dashboard</span>
                                </a>
                                <div class="dropdown-divider"></div>
                                <a href="{% url 'logout' %}" class="dropdown-item">
                                    <i class="ni ni-user-run"></i>
                                    <span>Logout</span>
                                </a>
                            </div>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>

templates/includes/side_navbar.html
{% load static %}
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand p-3 bold" href="{% url 'home' %}">
            <img src="{% static 'assets/img/brand/doctor-medical-mk-logo.png' %}" class="navbar-brand-img" alt="Brand logo"> <span class="h-100">MWA</span>
        </a>
        <!-- User -->
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="media align-items-center">
                    <span class="avatar avatar-sm rounded-circle">
                        <img alt="Image placeholder" src="https://ui-avatars.com/api/?name={{user.username}}">
                    </span>
                </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                <div class=" dropdown-header noti-title">
                    <h6 class="text-overflow m-0">Welcome!</h6>
                </div>
                <a href="#" class="dropdown-item">
                    <i class="ni ni-single-02"></i>
                    <span>My profile</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#!" class="dropdown-item">
                    <i class="ni ni-user-run"></i>
                    <span>Logout</span>
                </a>
                </div>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                <div class="col-6 collapse-brand">
                    <a href="{% url 'home' %}">
                    <img src="{% static 'assets/img/brand/doctor-medical-mk-logo.png' %}"> <span class="text-black-50">MWA</span>
                    </a>
                </div>
                <div class="col-6 collapse-close">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                    <span></span>
                    <span></span>
                    </button>
                </div>
                </div>
            </div>
            <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class=" nav-link" href="{% url 'records:dashboard' %}"> 
                        <i class="ni ni-tv-2 text-primary"></i> Dashboard
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'profiles:profile' %}">
                        <i class="ni ni-single-02 text-yellow"></i> User profile
                    </a>
                </li>
                {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'records:clinic-records' %}">
                            <i class="ni ni-bullet-list-67 text-red"></i> Records
                        </a>
                    </li>
                {% else %}
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'records:statistics' %}">
                        <i class="ni ni-chart-pie-35 text-red"></i> Statistics
                    </a>
                </li>
            </ul>
            <!-- Divider -->
            <hr class="my-3">
            <div class="position-relative bottom--8 d-flex flex-column justify-content-center align-items-center pt-4">
                <p class="position-relative text-center mb-0">Powered by</p>
                <br>
                <img src="{% static 'assets/img/brand/blue.png' %}" class="navbar-brand-img mt-0 pt-0" alt="Brand logo">
            </div>
        </div>
    </div>
</nav>